### ISSUE TITLE
Write a README

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda-cloud/camunda-cloud-testing#15]
**Description**

Currently the README does not have any contents. We should write a proper README that explains what this project can be used for and how to use it.

**Comment by remcowesterhoud** [comment]
Feedback received on the current README:

To start writing a test, I missed some clarification of the scope what I need to do. It was not immediately clear to me that the @ZeebeAssertion implicitly starts the test engine underneath. Could be solved by improved docs I think. Might also that I was searching to a ProcessEngineRule because I am used to JUnit < 5 (like step 2 in https://camunda.com/best-practices/testing-process-definitions/#_setup_your_test_with_recommended_test_classes_and_libraries). For me the blog post about C7 Junit 5 helped to clarify this - maybe that can serve as inspiration: https://camunda.com/blog/2021/01/test-your-processes-with-junit-5/

**Comment by remcowesterhoud** [comment]
Add a reference to EZE as a thank you for allowing us to copy their code.

**Comment by pihme** [comment]
Add a section on wait for idle state which explains how it works and why it might lead to flaky tests.

Also add a request for feedback specifically for this topic. 

(Maybe we need to make the default delay longer, maybe we need to make it configurable)
