### ISSUE TITLE
Add Deployment assertions

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda-cloud/camunda-cloud-testing#2]
**Description**

We would like to have assertions that enable us to assert specific conditions of a Deployment. Examples of some assertions could be:

- Verify a process has been deployed
- Verify the version of a deployed process 
- Verify the reason why a deployment has failed

**Comment by pihme** [comment]
This was implemented in two assertions:

* `DeploymentAssert` checks the deployment and allows to navigate to `ProcessAssert`
* `ProcessAssert` checks the process (e.g. version, resource name) and can also tell you whether the process has any instances

`ProcessAssert` is inspired by `ProcessDefinitionAssert` in BPMN Assert (https://github.com/camunda/camunda-bpm-assert/blob/master/core/src/main/java/org/camunda/bpm/engine/test/assertions/bpmn/ProcessDefinitionAssert.java)

Deviattions from BPMN assert:
* in BPMN assert you can assert the number of active instances, in our version you (currently) can only assert over the number of instances (active or not)

I think we could have a follow up issue to assert
* active instances
* terminated instances
* Completed instances

And so on. 

For now, I have limited the scope to the bare minimum.

See also #46 for additional ideas to expand the `ProcessAssert
