### ISSUE TITLE
Add Job assertions

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda-cloud/camunda-cloud-testing#3]
**Description**

We would like to have assertions that enable us to assert specific conditions of a Job. Examples of some assertions could be:

- Verify a job exists
- Verify the job type
- Verify the job process instance

**References**
[Camunda Playform Job assertions](https://github.com/camunda/camunda-bpm-assert/blob/master/core/src/main/java/org/camunda/bpm/engine/test/assertions/bpmn/JobAssert.java)
[Zeebe Worker Java Test Utilities project](https://github.com/camunda-community-hub/zeebe-worker-java-testutils)

**Comment by pihme** [comment]
Deviations from BPMNAssert

* `assertThat(job).hasId(id)` renamed to `assertThat(job).hasElementId(id)`
