### ISSUE TITLE
Add "wait for idle" support in the engine

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda-cloud/camunda-cloud-testing#6]
**Description**

If we want to test our processes we need to have a way to know when the engine has reached an idle state. Once this idle state is achieved we can start verifying the assertions. If we do not wait for this idle there would be a race condition where the assertion could be executed before the engine has finished processing the process.

As of now the engine has no way to indicate that it has reached an idle state. We need to figure out a way to recognise an idle state and to make the test client aware of it.

**Related issues**
#5 
Depends on #24

**Comment by pihme** [comment]
implemented as part of #24
